### PR TITLE
Bugfixes from @ericdill + integration with 'count_time'

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by ericdill** [comment]
Thanks for cleaning this up @danielballan . I hope this didn't take you too long...

**Comment by danielballan** [comment]
No problem -- it didn't take long. Will test at CHX momentarily.

**Comment by danielballan** [comment]
Travis 3.4 and 3.5 died on a DISPLAY-variable-related error. `matplotlib.use('Agg')` might fix.

**Comment by ericdill** [comment]
Wouldn't it be better to remove the plotting callbacks from the dscan/ascan/ct?

**Comment by ericdill** [comment]
Or you could add [these two lines] (https://github.com/NSLS-II/bluesky/blob/master/.travis.yml#L18-L19) to the travis yaml here

**Comment by danielballan** [comment]
Demo of this working at CHX:

* Set up global detectors, table columns, and new `gs.BASELINE_DEVICES`, devices to be read at the beginning and end.
* Run dscan without a `time` specified.
* Run another dscan with a 'time=2'.
* See the SPEC file.

```python

In [27]: gs.DETS = [xray_eye3]

In [28]: gs.BASELINE_DEVICES = [w1]

In [30]: gs.TABLE_COLS = [xray_eye3.stats1, diff_yh]

In [31]: s = DocumentToSpec('dan-tests-spec.txt')

In [32]: RE(dscan(diff.yh, -0.1, 0.1, 5), s)  # no 'time' given
Scan ID: 103
Unique ID: 57df6452-89ee-49e6-a11a-47a82b80bb7b
+-----------+------------+------------+-----------------------+
|   seq_num |       time |    diff_yh | diff_yh_user_setpoint |
+-----------+------------+------------+-----------------------+
|         1 | 15:30:28.5 |   -4.59986 |              -4.59370 | <-- a baseline reading
+-----------+------------+------------+-----------------------+------------------------+
|   seq_num |       time |    diff_yh | diff_yh_user_setpoint | xray_eye3_stats1_total |
+-----------+------------+------------+-----------------------+------------------------+
|         1 | 15:30:32.3 |   -4.70620 |              -4.69986 |                  51557 |
|         2 | 15:30:35.4 |   -4.65554 |              -4.65986 |                  51573 |
|         3 | 15:30:38.6 |   -4.61638 |              -4.61986 |                  51699 |
|         4 | 15:30:41.9 |   -4.57634 |              -4.57986 |                  51898 |
|         5 | 15:30:45.0 |   -4.53626 |              -4.53986 |                  51485 |
|         6 | 15:30:48.3 |   -4.49632 |              -4.49986 |                  51821 |
|         2 | 15:30:48.3 |   -4.49632 |              -4.49986 |                        |  <-- the second baseline reading
+-----------+------------+------------+-----------------------+------------------------+

In [33]: RE(dscan(diff.yh, -0.1, 0.1, 5, time=2)
(etc.)
```

The SPEC files has a header with info about `w1` and then two scans. Notice that `-1` is the placeholder value when the time is not specified. (pymca does not accept an non-numeric sentinel value like `None`.)

```
#F dan-tests-spec.txt
#E 1464377180
#D Fri May 27 15:26:20 2016
#C xf11id  User = xf11id
#O0 PV:XF:11IDB-OP{Win:1-Ax:X}Mtr.RBV  PV:XF:11IDB-OP{Win:1-Ax:X}Mtr.VAL  PV:XF:11IDB-OP{Win:1-Ax:Y}Mtr.RBV  PV:XF:11IDB-OP{Win:1-Ax:Y}Mtr.VAL
#o0 w1_x w1_x_user_setpoint w1_y w1_y_user_setpoint

#S 103 ascan diff_yh -0.1 0.1 6 -1
#D Fri May 27 15:30:28 2016
#T -1  (Seconds)
#P0 -4.5998600000000005 -4.5937 -0.0015 0.0002 -0.0002 -0.0001
#N 8
#L diff_yh  Epoch  Seconds  xray_eye3_stats1_total  xray_eye3_stats2_total  xray_eye3_stats3_total  xray_eye3_stats4_total  xray_eye3_stats5_total
-4.7062  1464377432 -1 51557.0 2719.0 243433.0 19444.0 11532791.0
-4.65554  1464377435 -1 51573.0 2712.0 244244.0 19567.0 11556402.0
-4.61638  1464377438 -1 51699.0 2771.0 242878.0 19277.0 11529576.0
-4.57634  1464377441 -1 51898.0 2772.0 243262.0 19139.0 11541864.0
-4.53626  1464377445 -1 51485.0 2754.0 244268.0 19260.0 11528669.0
-4.49632  1464377448 -1 51821.0 2790.0 243788.0 19371.0 11557760.0

#S 104 ascan diff_yh -0.1 0.1 4 2
#D Fri May 27 15:31:28 2016
#T 2  (Seconds)
#P0 -4.60616 -4.5998600000000005 -0.0015 0.0002 -0.0002 -0.0001
#N 8
#L diff_yh  Epoch  Seconds  xray_eye3_stats1_total  xray_eye3_stats2_total  xray_eye3_stats3_total  xray_eye3_stats4_total  xray_eye3_stats5_total
-4.7123800000000005  1464377492 2 51498.0 2795.0 243472.0 19543.0 11549318.0
-4.63332  1464377496 2 51307.0 2845.0 243082.0 19521.0 11564781.0
-4.56704  1464377499 2 51829.0 2747.0 244142.0 19209.0 11548960.0
-4.50016  1464377502 2 51663.0 2746.0 243603.0 19107.0 11518535.0
```

**Comment by ericdill** [comment]
:astonished: Wow it actually works!

**Comment by danielballan** [comment]
As it happens, @lwiegart dropped in at just the right time to test this SPEC file with pymca. It reads in just fine, and normalization (using our count_time) works as expected. :party:

**Comment by danielballan** [comment]
Travis, Lutz, and I are all happy, and this is mostly Eric's code, so I guess I'll be the one to push the merge button.

**Pull request merged**
