### PR TITLE
BLD/TST: Turn suitcase into a package. Verify the contents of the hdf5 export

### PR DESCRIPTION
**Pull request by ericdill**
I am turning this into a package so that I can add a spec.py file with the spec exporter and importer

### CODE REVIEW

**Comment by ericdill** [comment]
@danielballan the data stored in the hdf5 file is sorted with reverse chronological order. Is that the intent?  Consider the temperature ramp sample data code in metadatastore.  Running that example creates six events with these temperatures: 

```python
from metadatastore.examples.sample_data import temperature_ramp
from databroker import db, get_table
hdr = db[-1]
print(get_table(hdr).Tsam.dropna())

0    0.176405
1    1.145427
2    2.149408
3    3.065362
4    4.153278
5    5.123029
Name: Tsam, dtype: float64
```

but grabbing the data out of the exported hdf5 file shows the temperatures are sorted in reverse order:

```python
# using the same hdr as the code above
from suitcase import hdf_export
import h5py
import tempfile
fname = tempfile.NamedTemporaryFile()
hdf_export(hdf, fname.name)
with h5py.File(fname.name) as f:
    print(np.asarray(f['%s/%s/data/Tsam' % (hdr.start.uid, hdr.descriptors[0].uid)]))

array([ 5.12302907,  4.15327792,  3.06536186,  2.14940791,  1.14542735, 0.17640523])
```

**Comment by ericdill** [comment]
bah. edited the above comment because of a typo: s/hdf/hdr/

**Comment by ericdill** [comment]
Just turned on travis for this repo. Closed/opened to kick travis.

**Comment by danielballan** [comment]
I think suitcase should be returning events in chronological order (as MDS now does). So, I would say the current behavior is wrong and should be changed.

**Comment by ericdill** [comment]
Ok great. Will update. Thanks!

**Comment by ericdill** [comment]
> I think suitcase should be returning events in chronological order (as MDS now does). So, I would say the current behavior is wrong and should be changed.

Interestingly, `metadatastore.commands.find_events` returns the events newest first.

minimum reproducible example: https://gist.github.com/ericdill/11c77848fee4725efdef2a9d4e2fc2c6

attn @tacaswell

**Comment by ericdill** [comment]
or @arkilic

**Comment by ericdill** [comment]
Ok, this is pretty easy. Patch to mds incoming

**Comment by ericdill** [comment]
See NSLS-II/metadatastore#208 for the fix for this sorting issue. Sorry for the noise

**Comment by arkilic** [comment]
Changing the indexing direction in production systems tends to break things (e.g. chx). This makes me nervous. Let me know if we start getting OperationFailure(s). I can rebuild index tables if problems occurs.

**Comment by ericdill** [comment]
I'm not trying to fight you on this, but I don't understand your concern.  Is [the proposed change ] (https://github.com/NSLS-II/metadatastore/pull/208) in metadatastore touching the indexing direction?

**Comment by arkilic** [comment]
lol I know. CHX had issues because we have changed the indexing directions on resource datum, confusing the crap out of the back-end (hence, things worked in attempt number 4). I am more cautious changing the indexing directions myself. sharing experience is caring

**Comment by ericdill** [comment]
Ah thanks for clarifying.  Just to be clear, that patch to MDS isn't changing the indexing direction though, right?

**Comment by arkilic** [comment]
Yup, it does

**Comment by tacaswell** [comment]
can the usage be changed to use `get_events_generator` instead of `find_events`?

**Comment by arkilic** [comment]
@tacaswell whatever you guys decide to do upstream, let me know so I can modify the service accordingly

**Comment by tacaswell** [comment]
@arkilic This was an oversite on my part, I was mostly concerned with  `get_events_generator` and `get_events_table` and did not pay as close attention to `find_events`.

**Comment by ericdill** [comment]
Rebased to get rid of the crazy commit history from trying to debug this event ordering issue.  This should be good to go, assuming travis is happy

**Comment by ericdill** [comment]
@danielballan As the original author of this, can you make that this is still in line with the vision for `suitcase`? 

Here is a summary of the salient points of this PR.

1. Move `export()` into the hdf.py module.
2. Import `hdf.export()` in suitcase.__init__.py as `export()` and `hdf_export()`
3. Add tests for `hdf.export()` that verify that

    - the uid of the start document is in the hdf file
    - the start and stop documents in the hdf file are identical 
      to that in the header that comes out of the broker
    - each descriptor made it into the hdf file
    - each data key made it into the hdf file
    - the data is identical to the data that comes out of `databroker.get_table()`
    - the timestamps for each data key are identical to that in the event
      documents that come out of the broker
    - the event times are identical to the time column that is in 
      `databroker.get_table()`

4. Add `versioneer` to suitcase since it is now a full Python package

**Pull request merged**
